use mavenmovies;
/*Question 1: 
Retrieve the total number of rentals made in the Sakila database. Retrieve the total number of rentals made in the Sakila database*/
select count(rental_id) from rental;

/*Question 2: 
Find the average rental duration (in days) of movies rented from the Sakila database.*/
select avg(rental_duration) from film;

/*Question 3: 
Display the first name and last name of customers in uppercase. */
select upper(first_name) as FIRST_NAME, upper(last_name) as LAST_NAME from customer;

/*Question 4: 
Extract the month from the rental date and display it alongside the rental ID. */
select rental_id, month(rental_date) as rental_date_month from rental;

/*Question 5: 
Retrieve the count of rentals for each customer (display customer ID and the count of rentals).*/ 
select customer_id, count(rental_id) as count_of_rentals from rental group by customer_id;

/*Question 6: 
Find the total revenue generated by each store. */
select store.store_id, sum(amount) from store join staff on store.manager_staff_id = staff.staff_id join payment on staff.staff_id = payment.staff_id group by store_id;

/*Display the title of the movie, customer s first name, and last name who rented it. */
select film.title, customer.first_name, customer.last_name from film join inventory on film.film_id = inventory.film_id join rental on inventory.inventory_id = rental.inventory_id join customer on rental.customer_id = customer.customer_id;

/*Retrieve the names of all actors who have appeared in the film "Gone with the Wind." */
select actor.first_name, actor.last_name from film_actor join film on film_actor.film_id = film.film_id join actor on film_actor.actor_id = actor.actor_id where title = 'GONE TROUBLE';

/*Determine the total number of rentals for each category of movies. */
select category.name, count(rental_id) as total_number_of_rentals from category join film_category on category.category_id = film_category.category_id join film on film_category.film_id = film.film_id join inventory on film.film_id = inventory.film_id join rental on inventory.inventory_id = rental.inventory_id group by name;

/*Find the average rental rate of movies in each language. */
select language.name, avg(rental_rate) as average_rental_rate from film join language on film.language_id = language.language_id group by name;

/*Retrieve the customer names along with the total amount they've spent on rentals. */
select customer.first_name, customer.last_name, sum(amount) as amount_on_rentals from customer join payment on customer.customer_id = payment.customer_id join rental on payment.rental_id = rental.rental_id group by first_name,last_name;

/*List the titles of movies rented by each customer in a particular city (e.g., 'London'). */
select customer.first_name, customer.last_name, city.city, film.title from film join inventory on film.film_id = inventory.film_id join rental on inventory.inventory_id = rental.inventory_id join customer on rental.customer_id = customer.customer_id join address on customer.address_id = address.address_id join city on address.city_id = city.city_id;

/*Display the top 5 rented movies along with the number of times they've been rented. */
select film.title, count(rental_duration) as number_of_times_rented from film join inventory on film.film_id = inventory.film_id join rental on inventory.inventory_id = rental.inventory_id group by title limit 5;

/*Determine the customers who have rented movies from both stores (store ID 1 and store ID 2). */
